name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Fetch Tags
      run: git -c protocol.version=2 fetch --tags --progress --no-recurse-submodules origin
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Release Version
      id: get_version
      run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo ::set-output name=VERSION::$VERSION
    - name: Upload py-winrm-plugin zip
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: py-winrm-plugin-${{ steps.get_version.outputs.VERSION }}
        # Directory containing files to upload
        path: build/libs/py-winrm-plugin-${{ steps.get_version.outputs.VERSION }}-plugin.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Plugin (zip)
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./build/libs/py-winrm-plugin-${{ steps.get_version.outputs.VERSION }}-plugin.zip
        asset_name: py-winrm-plugin-${{ steps.get_version.outputs.VERSION }}-plugin.zip
        asset_content_type: application/zip

